---
# tasks file for ec2_creation
 - name: Create EC2 instances
   amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "{{key}}"
    instance_type: "{{instance_type}}"
    security_group: "{{security}}"
    region: "{{region}}"
    aws_access_key: "{{ec2_access_key}}"  # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
    # network:
    #   assign_public_ip: yes
    image_id: "{{ item.image }}"
        
   loop:
        - { image: "ami-0fff1b9a61dec8a5f", name: "manage-node-1" } # Update AMI ID according 
        - { image: "ami-0866a3c8686eaeeba", name: "manage-node-2" } # to your account
        - { image: "ami-0866a3c8686eaeeba", name: "manage-node-3" }
